version: '2.4'

services:
  nextcloud-ephemeral-master:
    build:
      context: .
      args:
        BRANCH: master
    ports:
      - "80:80"
  nextcloud-longlived-stable:
    build:
      context: .
      args:
        BRANCH: stable24
    ports:
      - "80:80"
    restart: always
    volumes:
      - nextcloud-stable:/var/www/html
      - apps-stable:/var/www/html/custom_apps
      - config-stable:/var/www/html/config
      - data-stable:/var/www/html/data
  nextcloud-ephemeral-stable:
    build:
      context: .
      args:
        BRANCH: stable24
    ports:
      - "80:80"
  nextcloud-talk-stable:
    build:
      context: .
      dockerfile: talk.Dockerfile
      args:
        BRANCH: stable24
    ports:
      - "80:80"
    volumes:
      - nextcloud-talk:/var/www/html
      - apps-talk:/var/www/html/custom_apps
      - config-talk:/var/www/html/config
      - data-talk:/var/www/html/data
  nextcloud-talk-master:
    build:
      context: .
      dockerfile: talk.Dockerfile
      args:
        BRANCH: master
    ports:
      - "80:80"

volumes:
  nextcloud-stable:
  apps-stable:
  config-stable:
  data-stable:

  nextcloud-talk:
  apps-talk:
  config-talk:
  data-talk: